// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RawAttr {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub raw_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EntityAttrs {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub attrs: ::prost::alloc::vec::Vec<RawAttr>,
}
/// RawAttr.raw_data の中身（ATTR_SKILL_LEVEL_ID_LIST）。スキル1枠分。
/// raw_data は SkillLevelList（repeated field 1 のタグ付き形式）。2026-07-10 ダンジョン実測で
/// タグ付き（0a …）形式と確定（旧実装の「(varint 長)(本体) 連結」は誤りで枠ズレしていた）。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkillLevelInfo {
    #[prost(int32, tag = "1")]
    pub skill_id: i32,
    #[prost(int32, tag = "2")]
    pub current_level: i32,
    #[prost(int32, tag = "3")]
    pub remodel_level: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkillLevelList {
    #[prost(message, repeated, tag = "1")]
    pub skills: ::prost::alloc::vec::Vec<SkillLevelInfo>,
}
/// RawAttr.raw_data の中身（ATTR_EQUIP_DATA=200）。装備1枠分。
/// raw_data は EquipNineList（repeated field 1 のタグ付き形式。SkillLevelList と同様）。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EquipNine {
    #[prost(int32, tag = "1")]
    pub slot: i32,
    #[prost(int32, tag = "2")]
    pub equip_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EquipNineList {
    #[prost(message, repeated, tag = "1")]
    pub equips: ::prost::alloc::vec::Vec<EquipNine>,
}
/// SceneDelta.effects(field 3) の要素
/// duration_ms: 0/未設定=無期限、-1=永続、>0=ミリ秒の持続時間
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimedEffect {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub activated_at: i64,
    #[prost(int64, tag = "3")]
    pub duration_ms: i64,
    #[prost(int64, tag = "4")]
    pub flag: i64,
    #[prost(int64, tag = "5")]
    pub extra: i64,
}
/// buff_list の 1 要素 (= BuffEffect)。
/// event_type は EBuffEventType (1=AddTo, 2=Remove, 4=Timer, 5=StackLayer …)、
/// buff_uuid は対象バフのインスタンスキー、body_raw は LogicEffect (= BuffPayload) の bytes。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffEvent {
    #[prost(int32, tag = "1")]
    pub event_type: i32,
    #[prost(int32, tag = "2")]
    pub buff_uuid: i32,
    #[prost(int64, tag = "3")]
    pub host_uuid: i64,
    #[prost(bytes = "vec", tag = "5")]
    pub body_raw: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuffEventBatch {
    #[prost(message, repeated, tag = "2")]
    pub buffs: ::prost::alloc::vec::Vec<BuffEvent>,
}
/// BuffEvent.body_raw をラップ (= BuffEffectLogicInfo)。
/// buff_type は EffectType (18=AddBuff→BuffSnapshot / 19=BuffChange)。
/// detail_raw は型ごとにアプリ側でデコードする。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffPayload {
    #[prost(int32, tag = "1")]
    pub buff_type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub detail_raw: ::prost::alloc::vec::Vec<u8>,
}
/// LogicEffect.EffectType==19 (BuffChange) の RawData。スタック増加/タイマー更新を表す。
/// base_id を持たず、対象は BuffEvent.buff_uuid で識別する。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffChange {
    #[prost(int32, tag = "1")]
    pub layer: i32,
    #[prost(int64, tag = "2")]
    pub duration: i64,
    #[prost(int64, tag = "3")]
    pub create_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDelta {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, optional, tag = "2")]
    pub attrs: ::core::option::Option<EntityAttrs>,
    #[prost(message, optional, tag = "10")]
    pub buff_list: ::core::option::Option<BuffEventBatch>,
    #[prost(message, optional, tag = "7")]
    pub skill_effects: ::core::option::Option<SkillImpact>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalSceneDelta {
    #[prost(message, optional, tag = "1")]
    pub base_delta: ::core::option::Option<SceneDelta>,
    #[prost(message, repeated, tag = "3")]
    pub effects: ::prost::alloc::vec::Vec<TimedEffect>,
    #[prost(int64, tag = "5")]
    pub uuid: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlayerProfile {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
    #[prost(string, tag = "2")]
    pub account_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "35")]
    pub fight_point: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerSnapshot {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
    #[prost(message, optional, tag = "2")]
    pub char_base: ::core::option::Option<PlayerProfile>,
    #[prost(message, optional, tag = "3")]
    pub scene_data: ::core::option::Option<WorldLocation>,
    #[prost(message, optional, tag = "7")]
    pub item_package: ::core::option::Option<InvBags>,
    #[prost(message, optional, tag = "12")]
    pub equip: ::core::option::Option<EquipList>,
    #[prost(message, optional, tag = "57")]
    pub r#mod: ::core::option::Option<ModuleSet>,
    #[prost(message, optional, tag = "61")]
    pub profession_list: ::core::option::Option<ClassState>,
}
/// 装備中スロット一覧（CharSerialize.equip）。key=装備スロット番号。
/// バトルイマジン枠の item_uuid を item_package(パッケージ type 6=バトルイマジン)の
/// アイテムと突合すると、装備中イマジンのアイテム構成ID(config_id)が引ける。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EquipList {
    #[prost(map = "int32, message", tag = "1")]
    pub equip_list: ::std::collections::HashMap<i32, EquipInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EquipInfo {
    #[prost(int32, tag = "1")]
    pub equip_slot: i32,
    #[prost(uint64, tag = "2")]
    pub item_uuid: u64,
    #[prost(int32, tag = "3")]
    pub equip_slot_refine_level: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EntityVanish {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EntityAppear {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(enumeration = "EntityKind", tag = "2")]
    pub ent_type: i32,
    #[prost(message, optional, tag = "3")]
    pub attrs: ::core::option::Option<EntityAttrs>,
    /// AOI 出現時点で既に付与されている既存バフ一覧（食事/シロップ等）。参照実装
    /// (../resonance-logs-cn の blueprotobuf_package.rs) の BuffInfoSync
    /// { int64 uuid = 1; repeated BuffInfo buff_infos = 2; } と同型。これが無いと
    /// appear の時点でバフを知る経路が無く、ダンジョンで先に食事していた他プレイヤーの
    /// 食事/シロップにバッジが出ない（グローバル版で実際に field 7 が来るかは
    /// 2026-08時点で probe 未確認。配線して到来ログで検証する）。
    #[prost(message, optional, tag = "7")]
    pub buff_infos: ::core::option::Option<BuffSnapshotBundle>,
}
/// EnterScene (WorldNtf method 0x3): 自キャラ入場時に届くフル属性スナップショット。
/// PlayerEnt(=自キャラ Entity) の attrs に、会心/ファスト/万能/知力/敏捷/魔攻/魔防 等の
/// 詳細ステータスが入る（SyncNearEntities の AOI 同期には含まれない）。
/// PlayerEnt は EntityAppear と同型(uuid=1, ent_type=2, attrs=3)なので再利用する。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnterScene {
    #[prost(message, optional, tag = "1")]
    pub enter_scene_info: ::core::option::Option<EnterSceneInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnterSceneInfo {
    #[prost(message, optional, tag = "2")]
    pub player_ent: ::core::option::Option<EntityAppear>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvItem {
    #[prost(int32, tag = "2")]
    pub config_id: i32,
    #[prost(message, optional, tag = "13")]
    pub mod_new_attr: ::core::option::Option<ModuleAttrs>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvBags {
    #[prost(map = "int32, message", tag = "1")]
    pub packages: ::std::collections::HashMap<i32, InvBag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModuleSet {
    #[prost(map = "int64, message", tag = "2")]
    pub mod_infos: ::std::collections::HashMap<i64, ModuleEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModuleEntry {
    #[prost(int32, repeated, tag = "4")]
    pub init_link_nums: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModuleAttrs {
    #[prost(int32, repeated, tag = "1")]
    pub mod_parts: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SocialEnvelope {
    #[prost(message, optional, tag = "1")]
    pub v_request: ::core::option::Option<SocialRequest>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SocialRequest {
    #[prost(message, optional, tag = "1")]
    pub data: ::core::option::Option<SocialBody>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvBag {
    #[prost(map = "int64, message", tag = "4")]
    pub items: ::std::collections::HashMap<i64, InvItem>,
}
/// プロフェッション（職業）状態。ログイン時の SyncContainerData(0x15) に載るため、発動に
/// 依存せず自キャラの装備イマジンが分かる（実機確認済 2026-07-10）:
/// - aoyi_skill_info_map: 習得済み奥義/絶技（＝バトルイマジン）の全コレクション。
///    key=skill_id（canonical 39xx）、value に凸数(remodel_level)。装備中とは限らない。
/// - profession_list\[cur_profession_id\].slot_skill_info_map: 現在職業の装備スロット→skill_id。
///    このうち skill_id が aoyi_skill_info_map に載っているものが装備中バトルイマジン。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClassState {
    #[prost(int32, tag = "1")]
    pub cur_profession_id: i32,
    #[prost(map = "int32, message", tag = "4")]
    pub profession_list: ::std::collections::HashMap<i32, ProfessionInfo>,
    #[prost(map = "int32, message", tag = "7")]
    pub aoyi_skill_info_map: ::std::collections::HashMap<i32, ProfessionSkillInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProfessionInfo {
    #[prost(int32, tag = "1")]
    pub profession_id: i32,
    #[prost(map = "int32, int32", tag = "7")]
    pub slot_skill_info_map: ::std::collections::HashMap<i32, i32>,
}
/// 装備スキル1枠分（remodel_level=イマジンレベル/凸数）。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProfessionSkillInfo {
    #[prost(int32, tag = "1")]
    pub skill_id: i32,
    #[prost(int32, tag = "2")]
    pub level: i32,
    #[prost(int32, tag = "4")]
    pub remodel_level: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorldLocation {
    #[prost(uint32, tag = "6")]
    pub level_map_id: u32,
    #[prost(uint32, tag = "15")]
    pub line_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkillImpact {
    #[prost(message, repeated, tag = "2")]
    pub damages: ::prost::alloc::vec::Vec<DamageRecord>,
}
/// char_id(=uid) は他の SocialData 系メッセージ（PlayerSnapshot 等）と同じ tag1 の想定
/// （参照実装のプロトコル定義由来の推定。実機のバイト列では未確認）。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SocialBody {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
    #[prost(message, optional, tag = "10")]
    pub scene_data: ::core::option::Option<WorldLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorldEnterSnapshot {
    #[prost(message, optional, tag = "1")]
    pub v_data: ::core::option::Option<PlayerSnapshot>,
}
/// WorldNtf method 0x2B。ゲームクライアント（＝当アプリと同一PC）とサーバの時刻同期。
/// client_milliseconds - server_milliseconds が「ローカル壁時計 − サーバ時計」の正確値
/// （buff_tracker の server_clock_offset_ms と同じ定義）。参照実装
/// ../resonance-logs-cn の blueprotobuf_package.rs:5703-5708
/// (SyncServerTime = 0x2B)。docs-private/protocol-map-transition-data.md では未マップ
/// opcode 0x2b としてダンジョン1周62回の高頻度到来を記録済み。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncServerTime {
    #[prost(int64, tag = "1")]
    pub client_milliseconds: i64,
    #[prost(int64, tag = "2")]
    pub server_milliseconds: i64,
}
/// WorldNtf method 0x17。ダンジョンの状態同期。マスター難易度の段階は
/// v_data.dungeon_scene_info.difficulty で届く。2026-09-30 の実機ログでは、ゲームのマスター6 で
/// difficulty=6（アプリの表示もマスター難易度6）だった。観測した遷移（町・フィールド・蝕ティナの
/// ノーマル/ハード/マスター）では届き、町・フィールド・ノーマル/ハードでは difficulty=0。
/// SocialEnvelope の後に、計測中（非停止）の1クライアントでは学習済みの自キャラ conn から届いた。
/// メッセージ定義は参照実装のプロトコル定義由来（SyncDungeonData.v_data=1 /
/// DungeonSyncData.dungeon_scene_info=21 / DungeonSceneInfo.difficulty=1）。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncDungeonData {
    #[prost(message, optional, tag = "1")]
    pub v_data: ::core::option::Option<DungeonSyncData>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DungeonSyncData {
    #[prost(message, optional, tag = "21")]
    pub dungeon_scene_info: ::core::option::Option<DungeonSceneInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DungeonSceneInfo {
    #[prost(int32, tag = "1")]
    pub difficulty: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DamageRecord {
    #[prost(bool, tag = "2")]
    pub is_miss: bool,
    #[prost(enumeration = "DmgKind", tag = "4")]
    pub r#type: i32,
    #[prost(int32, tag = "5")]
    pub type_flag: i32,
    #[prost(int64, tag = "6")]
    pub value: i64,
    #[prost(int64, tag = "8")]
    pub lucky_value: i64,
    #[prost(int64, tag = "9")]
    pub hp_lessen_value: i64,
    #[prost(int64, tag = "11")]
    pub attacker_uuid: i64,
    #[prost(int32, tag = "12")]
    pub owner_id: i32,
    #[prost(bool, tag = "17")]
    pub is_dead: bool,
    #[prost(int32, tag = "18")]
    pub property: i32,
    #[prost(int64, tag = "21")]
    pub top_summoner_id: i64,
    #[prost(int32, tag = "25")]
    pub damage_mode: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorldDeltaBatch {
    #[prost(message, repeated, tag = "1")]
    pub delta_infos: ::prost::alloc::vec::Vec<SceneDelta>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorldEntityBatch {
    #[prost(message, repeated, tag = "1")]
    pub appear: ::prost::alloc::vec::Vec<EntityAppear>,
    #[prost(message, repeated, tag = "2")]
    pub disappear: ::prost::alloc::vec::Vec<EntityVanish>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalDeltaBatch {
    #[prost(message, optional, tag = "1")]
    pub delta_info: ::core::option::Option<LocalSceneDelta>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Vec3f {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub z: f32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CombatOrigin {
    #[prost(int32, tag = "1")]
    pub fight_source_type: i32,
    #[prost(int32, tag = "2")]
    pub source_config_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffSnapshot {
    #[prost(int32, tag = "1")]
    pub buff_uuid: i32,
    #[prost(int32, tag = "2")]
    pub base_id: i32,
    #[prost(int32, tag = "3")]
    pub level: i32,
    #[prost(int64, tag = "4")]
    pub host_uuid: i64,
    #[prost(int32, tag = "5")]
    pub table_uuid: i32,
    #[prost(int64, tag = "6")]
    pub create_time: i64,
    #[prost(int64, tag = "7")]
    pub fire_uuid: i64,
    #[prost(int32, tag = "8")]
    pub layer: i32,
    #[prost(int32, tag = "9")]
    pub part_id: i32,
    #[prost(int32, tag = "10")]
    pub count: i32,
    #[prost(int32, tag = "11")]
    pub duration: i32,
    #[prost(message, optional, tag = "12")]
    pub fight_source_info: ::core::option::Option<CombatOrigin>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuffSnapshotBundle {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub buff_infos: ::prost::alloc::vec::Vec<BuffSnapshot>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffTick {
    #[prost(int64, tag = "1")]
    pub host_uuid: i64,
    #[prost(int32, tag = "2")]
    pub buff_uuid: i32,
    #[prost(int32, tag = "3")]
    pub base_id: i32,
    #[prost(int64, tag = "4")]
    pub duration: i64,
    #[prost(int64, tag = "5")]
    pub create_time: i64,
    #[prost(int32, tag = "6")]
    pub layer: i32,
}
/// TeamNtf method 0x1。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NoticeUpdateTeamInfo {
    #[prost(message, optional, tag = "1")]
    pub v_request: ::core::option::Option<NoticeUpdateTeamInfoRequest>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NoticeUpdateTeamInfoRequest {
    #[prost(message, optional, tag = "1")]
    pub base_info: ::core::option::Option<TeamBaseInfo>,
}
/// TeamNtf method 0x2。ダンジョン1周60回程度の高頻度到来が実測されている
/// （processor.rs 側でメンバー構成/team_id 変化時のみログする）。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NoticeUpdateTeamMemberInfo {
    #[prost(message, optional, tag = "1")]
    pub v_request: ::core::option::Option<NoticeUpdateTeamMemberInfoRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NoticeUpdateTeamMemberInfoRequest {
    #[prost(message, repeated, tag = "5")]
    pub team_member_sync_datas: ::prost::alloc::vec::Vec<TeamMemberFastSyncData>,
    #[prost(message, repeated, tag = "6")]
    pub team_member_social_datas: ::prost::alloc::vec::Vec<TeamMemData>,
}
/// TeamNtf method 0x3。PT参加。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotifyJoinTeam {
    #[prost(message, optional, tag = "1")]
    pub v_request: ::core::option::Option<NotifyJoinTeamRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotifyJoinTeamRequest {
    #[prost(message, optional, tag = "1")]
    pub base_info: ::core::option::Option<TeamBaseInfo>,
    #[prost(message, repeated, tag = "2")]
    pub member_data: ::prost::alloc::vec::Vec<TeamMemData>,
    #[prost(map = "int64, message", tag = "6")]
    pub member_sync_datas: ::std::collections::HashMap<i64, TeamMemberFastSyncData>,
}
/// TeamNtf method 0x4。PT離脱（自分/他人とも同一メッセージ形。char_id で判別する）。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyLeaveTeam {
    #[prost(message, optional, tag = "1")]
    pub v_request: ::core::option::Option<NotifyLeaveTeamRequest>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyLeaveTeamRequest {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
    #[prost(int32, tag = "2")]
    pub leave_type: i32,
}
/// TeamNtf method 0xd。PT解散。リクエストは空メッセージ。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NoticeTeamDissolve {
    #[prost(message, optional, tag = "1")]
    pub v_request: ::core::option::Option<NoticeTeamDissolveRequest>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NoticeTeamDissolveRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TeamBaseInfo {
    #[prost(int64, tag = "1")]
    pub team_id: i64,
    #[prost(int64, tag = "3")]
    pub leader_id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TeamMemData {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TeamMemberFastSyncData {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DmgKind {
    Normal = 0,
    Miss = 1,
    Heal = 2,
}
impl DmgKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Normal => "Normal",
            Self::Miss => "Miss",
            Self::Heal => "Heal",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Normal" => Some(Self::Normal),
            "Miss" => Some(Self::Miss),
            "Heal" => Some(Self::Heal),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EntityKind {
    Unknown = 0,
    Monster = 1,
    Player = 10,
}
impl EntityKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::Monster => "Monster",
            Self::Player => "Player",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unknown" => Some(Self::Unknown),
            "Monster" => Some(Self::Monster),
            "Player" => Some(Self::Player),
            _ => None,
        }
    }
}
